name: pull_docker_image
on: 
  workflow_dispatch:
    inputs:
        img:
          description: "image to download, for instance, zlmediakit/zlmediakit:master"
          required: true

jobs:
  docker_pull:
    name: docker拉取镜像打包
    runs-on: ubuntu-latest
  
    steps:
    - uses: actions/checkout@v4
    
    - env:
          IMG: ${{ github.event.inputs.img }}
    - run: echo  ${{ IMG }}
    
    - run: pip install aligo
    - run: mkdir dockerimages
    - run: docker pull ${{ IMG }}
    - run: docker images
    - run: docker save -o docker_image.tar ${{ IMG }}
    - run: mv docker_image.tar dockerimages/docker_image.tar
    - run: python pull_docker_image/uploadAlipan.py ${{ secrets.ALIYUNPAN_REFRESH_TOKEN }} $(pwd)/dockerimages
