name: Pull_Zlm
on: workflow_dispatch
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: ls

  example-2job:
    runs-on: ubuntu-latest
    steps:
    - run: pwd
    - run: ls
