name: Pull_docker_image
on: workflow_dispatch
jobs:
  docker_pull:
    name: docker拉取镜像打包
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    - run: pip install aligo
    - run: mkdir dockerimages
    - run: docker pull ${{ DOCKER_IMAGE_NAME }}
    - run: docker images
    - run: docker save -o docker_image.tar ${{ DOCKER_IMAGE_NAME }}
    - run: mv docker_image.tar dockerimages/docker_image.tar
    - run: folder_path=$(pwd)/dockerimages
    - run: python uploadAlipan.py ${{ALIYUNPAN_REFRESH_TOKEN}} $folder_path
